### ISSUE TITLE
Asset being uploaded before backgrounder gets to it on update

### ISSUE THREAD

**Issue by jvsidler** [lardawge/carrierwave_backgrounder#144]
ruby 2.0.0-p0
Carrierwave 0.8.0
Carrierwave_backgrounder 0.2.1
Rails 4.0.0.rc1
Sidekiq 2.12.0
Redis 3.0.4
Fog 1.11.1

Using store_in_background

When I attempt to update a video:

File is uploaded to cache
Record gets the tmp column updated
File is uploaded to Rackspace Cloudfiles as if backgrounder wasn't being used
Then sidekiq attempts to update file on Cloudfiles but can't find the resource since the file now has a new name from the upload that happened before backgrounder attempted to update the resource.

Controller update action:

``` ruby
def update
  if @video.update(video_params)
    redirect_to edit_admin_video_path(@video), notice: 'Video was successfully updated.'
  else
    render action: 'edit'
  end
end
```

Uploader class:

``` ruby
class VideoUploader < CarrierWave::Uploader::Base
  include ::CarrierWave::Backgrounder::Delay

  storage :fog

  def store_dir
    "#{@model.class.to_s.underscore.pluralize}/#{@model.id}/#{@mounted_as.to_s}"
  end

  def extension_white_list
    %w(mp4)
  end

end
```

Video class:

``` ruby
require 'carrierwave/orm/activerecord'

class Video < ActiveRecord::Base
  ...
  mount_uploader :file_url, VideoUploader
  store_in_background :file_url
  ...
end
```

**Comment by pencilcheck** [comment]
I am getting a lot of errors from backgrounders about not able to find a temp file, perhaps the same problem? Since it make sense if the files has been uploaded before sidekiq get a chance to process it.


```
E, [2015-02-21T21:17:02.258660 #16795] ERROR -- : Actor crashed!
CarrierWave::ProcessingError: Failed to manipulate with MiniMagick, maybe it is not an image? Original Error: Command ("mogrify -resize 200x200 /tmp/mini_magick20150221-16795-4ox14p.jpg") failed: {:status_code=>nil, :output=>""}
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/processing/mini_magick.rb:273:in `rescue in manipulate!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/processing/mini_magick.rb:259:in `manipulate!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/processing/mini_magick.rb:153:in `resize_to_fit'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/processing.rb:84:in `block in process!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/processing.rb:76:in `each'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/processing.rb:76:in `process!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave_backgrounder-0.4.1/lib/backgrounder/delay.rb:14:in `process!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:18:in `block in with_callbacks'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:18:in `each'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:18:in `with_callbacks'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:122:in `cache!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/versions.rb:226:in `recreate_versions!'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/carrierwave_backgrounder-0.4.1/lib/backgrounder/workers/process_asset.rb:12:in `perform'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:365:in `perform_action_with_newrelic_trace'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.3.241/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-unique-jobs-3.0.11/lib/sidekiq_unique_jobs/middleware/server/unique_jobs.rb:17:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-failures-0.4.3/lib/sidekiq/failures/middleware.rb:9:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
        /var/www/wwm/releases/37/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```
