### ISSUE TITLE
Not loading fog configuration.

### ISSUE THREAD

**Issue by florida** [lardawge/carrierwave_backgrounder#168]
I upload my files to s3, so I have an initializer that configures the fog credentials.

My app's uploads works without backgrounder, but when I added backgrounder + resque it it seemed to have broken it.

The error that it's displaying is: 

`Missing required arguments: aws_access_key_id, aws_secret_access_key`

Extended error message:

```
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/fog-1.18.0/lib/fog/core/service.rb:208:in `validate_options'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/fog-1.18.0/lib/fog/core/service.rb:58:in `new'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/fog-1.18.0/lib/fog/storage.rb:22:in `new'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/storage/fog.rb:102:in `connection'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/storage/fog.rb:355:in `connection'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/storage/fog.rb:367:in `directory'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/storage/fog.rb:382:in `file'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/storage/fog.rb:227:in `read'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/uploader/cache.rb:77:in `sanitized_file'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/uploader/cache.rb:116:in `cache!'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave-0.9.0/lib/carrierwave/uploader/versions.rb:225:in `recreate_versions!'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave_backgrounder-0.3.0/lib/backgrounder/workers/process_asset.rb:12:in `perform'
/opt/boxen/rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/carrierwave_backgrounder-0.3.0/lib/backgrounder/workers/base.rb:6:in `perform'
```

I followed the setup, I'm not sure if there's anything I missed or any special configuration for fog configuration.

**Comment by ckgagan** [comment]
I ran into the same situation when I tried the command
rails g carrierwave_backgrounder:install

I have the same initializer file that @florida  had.
What have I missed?

**Comment by loriculberson** [comment]
@florida I know its been a while, but can  you explain your solution by running ``rake resque:setup``` to load the rails environment.
