### ISSUE TITLE
undefined method `configure' for CarrierWave::Backgrounder:Module (NoMethodError)

### ISSUE THREAD

**Issue by edenisn** [lardawge/carrierwave_backgrounder#267]
I use rails 5.1 and when I try to run rails s... I get this error:
```
config/initializers/carrierwave_backgrounder.rb:1:in `<top (required)>': undefined method `configure' for CarrierWave::Backgrounder:Module (NoMethodError)
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:74:in `load'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `block in load'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:286:in `load'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:168:in `instrument'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:654:in `load_config_initializer'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:611:in `each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/initializable.rb:58:in `run_initializers'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/application.rb:353:in `initialize!'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/railtie.rb:185:in `public_send'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/railtie.rb:185:in `method_missing'
	from /Users/edenisn/notesolution/oneclass/config/environment.rb:7:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from config.ru:3:in `block in <main>'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:24:in `app'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:42:in `start'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:6:in `require'
	from bin/rails:6:in `<main>'
```

**Comment by paxer** [comment]
try in your Gemfile to point bundler to a master branch like
```
gem 'carrierwave_backgrounder', :github => 'lardawge/carrierwave_backgrounder'
```

otherwise for some reasons by default it install version 0.0.2

**Comment by edenisn** [comment]
Okay. Thanks Pavel!

**Comment by abdulhanan001** [comment]
> try in your Gemfile to point bundler to a master branch like
> 
> ```
> gem 'carrierwave_backgrounder', :github => 'lardawge/carrierwave_backgrounder'
> ```
> 
> otherwise for some reasons by default it install version 0.0.2


Thanks for solution. But after that Getting error` undefined method `perform' for CarrierWave::Workers::StoreAsset:Class`
and I prersonally read the carrierwave_backgrounder gemfile its looks like solved
what can be issue under the hood
